-- Generated by nwg-displays on 2026-01-19 at 14:51:39. Do not edit manually. (Migrated to Lua)

hl.monitor({ output = "eDP-1", mode = "2560x1600@60.0", position = "0x0", scale = "1.6" })
hl.monitor({ output = "DP-1", mode = "2560x1440@180.0", position = "1600x0", scale = "1.0" })
